"""Load, split, and preprocess the fraud dataset."""

from __future__ import annotations

import argparse
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from config import (
    DATA_PROCESSED_DIR,
    PREPROCESSED_DATA_PATH,
    PREPROCESSOR_PATH,
    RANDOM_STATE,
    RAW_DATA_PATH,
    RAW_TEST_PATH,
    RAW_TRAIN_PATH,
    TARGET_CANDIDATES,
    TEST_SIZE,
)
from utils import ensure_directories, set_seed


def _drop_auxiliary_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Drop autogenerated index columns that should not be model features."""
    unnamed_cols = [col for col in df.columns if col.lower().startswith("unnamed:")]
    if unnamed_cols:
        return df.drop(columns=unnamed_cols)
    return df


def _infer_target_column(df: pd.DataFrame) -> str:
    """Infer the target column name from known candidates."""
    for candidate in TARGET_CANDIDATES:
        if candidate in df.columns:
            return candidate
    raise ValueError(
        f"Could not find target column. Expected one of: {TARGET_CANDIDATES}, "
        f"but got columns: {list(df.columns)}"
    )


def _load_csv(csv_path: Path) -> pd.DataFrame:
    """Load one CSV file and apply minimal structural cleanup."""
    if not csv_path.exists():
        raise FileNotFoundError(f"Dataset file not found: {csv_path}")
    return _drop_auxiliary_columns(pd.read_csv(csv_path))


def _resolve_paths(data_path: Path) -> tuple[Path | None, Path | None, Path | None]:
    """Resolve train/test paths or single combined CSV path."""
    if data_path.is_dir():
        train_path = data_path / "fraudTrain.csv"
        test_path = data_path / "fraudTest.csv"
        combined_path = data_path / "creditcard.csv"
    else:
        train_path = None
        test_path = None
        combined_path = data_path

        lower_name = data_path.name.lower()
        sibling_train = data_path.parent / "fraudTrain.csv"
        sibling_test = data_path.parent / "fraudTest.csv"
        if lower_name in {"fraudtrain.csv", "fraudtest.csv"} and sibling_train.exists() and sibling_test.exists():
            train_path = sibling_train
            test_path = sibling_test
            combined_path = None

    if train_path is not None and test_path is not None and train_path.exists() and test_path.exists():
        return train_path, test_path, None

    if combined_path is not None and combined_path.exists():
        return None, None, combined_path

    raise FileNotFoundError(
        "Could not resolve dataset files. Expected either:\n"
        "1) data/raw/fraudTrain.csv and data/raw/fraudTest.csv, or\n"
        "2) a single combined CSV file path."
    )


def load_train_test_frames(data_path: Path) -> tuple[pd.DataFrame, pd.DataFrame | None, str, str]:
    """Load train/test frames when available, otherwise a single frame."""
    train_path, test_path, combined_path = _resolve_paths(data_path)

    if train_path is not None and test_path is not None:
        train_df = _load_csv(train_path)
        test_df = _load_csv(test_path)
        target_column = _infer_target_column(train_df)
        if target_column not in test_df.columns:
            raise ValueError(
                f"Target column '{target_column}' exists in train file but not in test file."
            )
        return train_df, test_df, target_column, "provided_train_test_files"

    if combined_path is None:
        raise RuntimeError("Unexpected dataset path state.")
    df = _load_csv(combined_path)
    target_column = _infer_target_column(df)
    return df, None, target_column, "single_file"


def load_data(data_path: Path) -> pd.DataFrame:
    """Load a dataframe for analysis; combines train/test files if both exist."""
    train_df, test_df, _, _ = load_train_test_frames(data_path)
    if test_df is None:
        return train_df
    return pd.concat([train_df, test_df], ignore_index=True)


def split_data(
    df: pd.DataFrame,
    target_column: str,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series]:
    """Create a stratified train/test split for imbalanced fraud labels."""
    X = df.drop(columns=[target_column])
    y = df[target_column].astype(int)

    # Stratification preserves rare fraud ratio in both train and test sets.
    return train_test_split(
        X,
        y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=y,
    )


def load_dataset_splits(
    data_path: Path,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.Series, pd.Series, str, str]:
    """Load raw train/test splits from files, or derive stratified split from one file."""
    train_df, test_df, target_column, source_mode = load_train_test_frames(data_path)

    if test_df is None:
        X_train, X_test, y_train, y_test = split_data(train_df, target_column=target_column)
        split_method = "stratified_train_test_split"
    else:
        X_train = train_df.drop(columns=[target_column])
        y_train = train_df[target_column].astype(int)
        X_test = test_df.drop(columns=[target_column])
        y_test = test_df[target_column].astype(int)
        split_method = "provided_train_test_files"

    # Keep only columns shared by both splits.
    common_features = [col for col in X_train.columns if col in X_test.columns]
    X_train = X_train[common_features].copy()
    X_test = X_test[common_features].copy()
    return X_train, X_test, y_train, y_test, target_column, source_mode if source_mode != "single_file" else split_method


def select_numeric_features(
    X_train: pd.DataFrame,
    X_test: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, list[str]]:
    """Keep numeric features only to avoid high-cardinality text leakage and memory issues."""
    numeric_features = X_train.select_dtypes(include=[np.number]).columns.tolist()
    if not numeric_features:
        raise ValueError("No numeric features available after loading dataset.")
    return X_train[numeric_features].copy(), X_test[numeric_features].copy(), numeric_features


def build_preprocessor(feature_names: list[str]) -> ColumnTransformer:
    """Build a simple numeric preprocessing pipeline."""
    numeric_pipeline = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", StandardScaler()),
        ]
    )
    return ColumnTransformer(
        transformers=[("numeric", numeric_pipeline, feature_names)],
        remainder="drop",
    )


def run_preprocessing(data_path: Path) -> Path:
    """Run preprocessing and save transformed train/test arrays."""
    set_seed(RANDOM_STATE)
    ensure_directories(DATA_PROCESSED_DIR)

    X_train, X_test, y_train, y_test, target_column, split_method = load_dataset_splits(data_path)
    X_train_num, X_test_num, feature_names = select_numeric_features(X_train, X_test)

    preprocessor = build_preprocessor(feature_names=feature_names)
    X_train_processed = preprocessor.fit_transform(X_train_num)
    X_test_processed = preprocessor.transform(X_test_num)

    np.savez_compressed(
        PREPROCESSED_DATA_PATH,
        X_train=X_train_processed,
        X_test=X_test_processed,
        y_train=y_train.to_numpy(),
        y_test=y_test.to_numpy(),
        feature_names=np.array(feature_names, dtype=object),
    )
    joblib.dump(preprocessor, PREPROCESSOR_PATH)

    split_info = pd.DataFrame(
        [
            {
                "split": "train",
                "n_rows": len(X_train),
                "fraud_rate": float(y_train.mean()),
                "split_method": split_method,
                "target_column": target_column,
            },
            {
                "split": "test",
                "n_rows": len(X_test),
                "fraud_rate": float(y_test.mean()),
                "split_method": split_method,
                "target_column": target_column,
            },
            {
                "split": "features",
                "n_rows": len(feature_names),
                "fraud_rate": np.nan,
                "split_method": "numeric_only_features",
                "target_column": target_column,
            },
        ]
    )
    split_info.to_csv(DATA_PROCESSED_DIR / "split_info.csv", index=False)
    return PREPROCESSED_DATA_PATH


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Preprocess fraud detection dataset.")
    parser.add_argument(
        "--data-path",
        default=str(RAW_DATA_PATH),
        help="Path to data/raw directory, or to a CSV file.",
    )
    return parser.parse_args()


def main() -> None:
    """CLI entry point for preprocessing."""
    args = parse_args()
    output_path = run_preprocessing(Path(args.data_path))
    print(f"Saved preprocessed arrays: {output_path}")
    print(f"Saved preprocessor: {PREPROCESSOR_PATH}")
    print(f"Expected default files: {RAW_TRAIN_PATH} and {RAW_TEST_PATH}")


if __name__ == "__main__":
    main()

